        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 24 15:20:57 2014
        MODULE CLUSTERSIZE_mod
          INTERFACE 
            SUBROUTINE CLUSTERSIZE
            END SUBROUTINE CLUSTERSIZE
          END INTERFACE 
        END MODULE CLUSTERSIZE_mod
