        !COMPILER-GENERATED INTERFACE MODULE: Mon May 14 12:28:50 2018
        MODULE CLUSTERSIZE__genmod
          INTERFACE 
            SUBROUTINE CLUSTERSIZE
            END SUBROUTINE CLUSTERSIZE
          END INTERFACE 
        END MODULE CLUSTERSIZE__genmod
