        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 24 15:20:56 2014
        MODULE DELTACALC_mod
          INTERFACE 
            SUBROUTINE DELTACALC
            END SUBROUTINE DELTACALC
          END INTERFACE 
        END MODULE DELTACALC_mod
