        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 24 15:20:56 2014
        MODULE KMINMAX_mod
          INTERFACE 
            SUBROUTINE KMINMAX
            END SUBROUTINE KMINMAX
          END INTERFACE 
        END MODULE KMINMAX_mod
