        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 24 15:20:56 2014
        MODULE LECT_CDATA_mod
          INTERFACE 
            SUBROUTINE LECT_CDATA(JBAND)
              INTEGER(KIND=4) :: JBAND
            END SUBROUTINE LECT_CDATA
          END INTERFACE 
        END MODULE LECT_CDATA_mod
