SUBROUTINE CALC_FLUXPLUSQ
USE ML1D_MOD
IMPLICIT NONE
DOUBLE PRECISION C1,C2,C3,C4,C5,C6,XX,YY,XXXX !LOCAL VARIABLES
DOUBLE PRECISION L !LOCAL VARIABLE
!GAS
!EVALUATE MATRIX INTXPKS
DO ICOL=1,NCOL
DO JCOL=ICOL,NCOL
INTXPKS(ICOL,JCOL)=0.D0
DO MCOL=ICOL,JCOL
INTXPKS(ICOL,JCOL)=INTXPKS(ICOL,JCOL)+KJ(MCOL)*DX(MCOL) !*LL/NCOL
END DO
END DO
END DO
!CALCULATE DIRECTIONAL FLUXES
C1=0.D0
C2=0.D0
C3=0.D0
C4=0.D0
C5=0.D0
C6=0.D0
XX=INTXPKS(1,NCOL)
CALL E3(XX,YY)
C1=2.D0*(EPSL*AJ(NCOL+1)*IB(NCOL+1)-AJ(NCOL)*IB(NCOL))*YY
DO MCOL=1,NCOL-1
XX=INTXPKS(1,MCOL)
CALL E3(XX,YY)
C2=C2+2.D0*(AJ(MCOL+1)*IB(MCOL+1)-AJ(MCOL)*IB(MCOL))*YY
ENDDO
XX=INTXPKS(1,NCOL)
CALL E3(XX,YY)
C1=2.D0*RHO0*YY*(C1+C2+AJ(1)*IB(1))
C3=2.D0*(EPS0*AJ(0)*IB(0)-AJ(1)*IB(1))*YY
DO MCOL=2,NCOL
XX=INTXPKS(MCOL,NCOL)
CALL E3(XX,YY)
C4=C4+2.D0*(AJ(MCOL-1)*IB(MCOL-1)-AJ(MCOL)*IB(MCOL))*YY
ENDDO
XX=INTXPKS(1,NCOL)
CALL E3(XX,YY)
FJP=(C1+C3+C4+AJ(NCOL)*IB(NCOL))*SIGMA/(1.D0-4.D0*RHO0*RHOL*YY*YY)
C1=0.D0
C2=0.D0
C3=0.D0
C4=0.D0
C5=0.D0
C6=0.D0
!FJM=FN0(J)
XX=INTXPKS(1,NCOL)
CALL E3(XX,YY)
C1=2.D0*(EPS0*AJ(0)*IB(0)-AJ(1)*IB(1))*YY
DO MCOL=2,NCOL
XX=INTXPKS(MCOL,NCOL)
CALL E3(XX,YY)
C2=C2+2.D0*(AJ(MCOL-1)*IB(MCOL-1)-AJ(MCOL)*IB(MCOL))*YY
ENDDO
C1=(C1+C2+AJ(NCOL)*IB(NCOL))
XX=INTXPKS(1,NCOL)
CALL E3(XX,YY)
C1=2.D0*RHOL*YY*C1
C2=2.D0*(EPSL*AJ(NCOL+1)*IB(NCOL+1)-AJ(NCOL)*IB(NCOL))*YY
DO MCOL=1,NCOL-1
XX=INTXPKS(1,MCOL)
CALL E3(XX,YY)
C3=C3+2.d0*(AJ(MCOL+1)*IB(MCOL+1)-AJ(MCOL)*IB(MCOL))*YY
ENDDO
XX=INTXPKS(1,NCOL)
CALL E3(XX,YY)
C1=(C1+C2+C3+AJ(1)*IB(1))
FJM=C1*SIGMA/(1.D0-4.D0*RHO0*RHOL*YY*YY)
!CALCULATION OF THE WALL NET FLUX.
XX=0.D0
CALL E3(XX,YY)
FP0=2*PI*(EPS0*AJ(0)*(IBN(0)**4.D0*SIGMA/PI)-AJ(2)*(IBN(2)**4.D0*SIGMA/PI)+RHO0/PI*FJM)*YY
XX=0.D0
DO ICOL=1,NCOL 
XX=XX+KJ(ICOL)*DX(ICOL)
ENDDO
CALL E3(XX,YY)
FPL=2*PI*(EPS0*AJ(0)*(IBN(0)**4.D0*SIGMA/PI)-AJ(2)*(IBN(2)**4.D0*SIGMA/PI)+RHO0/PI*FJM)*YY
XX=0.D0
CALL E3(XX,YY)
FNL=2*PI*(EPSL*AJ(NCOL+1)*(IBN(NCOL+1)**4.D0*SIGMA/PI)-AJ(2)*(IBN(2)**4.D0*SIGMA/PI)+RHOL/PI*FJP)*YY
XX=0.D0
DO ICOL=1,NCOL 
XX=XX+KJ(ICOL)*DX(ICOL)
ENDDO
CALL E3(XX,YY)
FN0=2*PI*(EPSL*AJ(NCOL+1)*(IBN(NCOL+1)**4.D0*SIGMA/PI)-AJ(2)*(IBN(2)**4.D0*SIGMA/PI)+RHOL/PI*FJP)*YY
!END OF THE CALCULATION OF THE WALL NET FLUX.
C1=0.D0
C2=0.D0
C3=0.D0
C4=0.D0
C5=0.D0
C6=0.D0
!Q(X1)
XX=KJ(1)*DX(1)/2.D0
CALL E2(XX,YY)
C1=(EPS0*AJ(0)*IB(0)-2.D0*AJ(1)*IB(1)+AJ(2)*IB(2)+RHO0*FJM/SIGMA)*YY
XX=KJ(1)*DX(1)/2.D0+INTXPKS(2,NCOL)
CALL E2(XX,YY)
C2=(EPSL*AJ(NCOL+1)*IB(NCOL+1)-AJ(NCOL)*IB(NCOL)+RHOL*FJP/SIGMA)*YY
C3=0.D0
DO MCOL=2,NCOL-1
XX=KJ(1)*DX(1)/2.D0+INTXPKS(2,MCOL)
CALL E2(XX,YY)
C3=C3+(AJ(MCOL+1)*IB(MCOL+1)-AJ(MCOL)*IB(MCOL))*YY
END DO
QJ(1)=2.D0*SIGMA*KJ(1)*(C1+C2+C3)
!Q(X2)
XX=KJ(1)*DX(1)+KJ(2)*DX(2)/2.D0
CALL E2(XX,YY)
C1=(EPS0*AJ(0)*IB(0)-AJ(1)*IB(1)+RHO0*FJM/SIGMA)*YY
XX=KJ(2)*DX(2)/2.D0+INTXPKS(3,NCOL)
CALL E2(XX,YY)
C2=(EPSL*AJ(NCOL+1)*IB(NCOL+1)-AJ(NCOL)*IB(NCOL)+RHOL*FJP/SIGMA)*YY
XX=KJ(2)*DX(2)/2.D0
CALL E2(XX,YY)
C3=(AJ(1)*IB(1)-2.D0*AJ(2)*IB(2)+AJ(3)*IB(3))*YY
C4=0.D0
DO MCOL=3,NCOL-1
XX=KJ(2)*DX(2)/2.D0+INTXPKS(3,MCOL)
CALL E2(XX,YY)
C4=C4+(AJ(MCOL+1)*IB(MCOL+1)-AJ(MCOL)*IB(MCOL))*YY
END DO
QJ(2)=2.D0*SIGMA*KJ(2)*(C1+C2+C3+C4)
!Q(XNCOL)
XX=KJ(NCOL)*DX(NCOL)/2.D0
CALL E2(XX,YY)
C1=(EPSL*AJ(NCOL+1)*IB(NCOL+1)-2.D0*AJ(NCOL)*IB(NCOL)+AJ(NCOL-1)*IB(NCOL-1)+RHOL*FJP/SIGMA)*YY
XX=KJ(NCOL)*DX(NCOL)/2.D0+INTXPKS(1,NCOL-1)
CALL E2(XX,YY)
C2=(EPS0*AJ(0)*IB(0)-AJ(1)*IB(1)+RHO0*FJM/SIGMA)*YY
C3=0.D0
DO MCOL=2,NCOL-1
XX=KJ(NCOL)*DX(NCOL)/2.D0+INTXPKS(MCOL,NCOL-1)
CALL E2(XX,YY)
C3=C3+(AJ(MCOL-1)*IB(MCOL-1)-AJ(MCOL)*IB(MCOL))*YY
END DO
QJ(NCOL)=2.D0*SIGMA*KJ(NCOL)*(C1+C2+C3)
!Q(XNCOL-1)
XX=KJ(NCOL)*DX(NCOL)+KJ(NCOL-1)*DX(NCOL-1)/2.D0
CALL E2(XX,YY)
C1=(EPSL*AJ(NCOL+1)*IB(NCOL+1)-AJ(NCOL)*IB(NCOL)+RHOL*FJP/SIGMA)*YY
XX=KJ(NCOL-1)*DX(NCOL-1)/2.D0+INTXPKS(1,NCOL-2)
CALL E2(XX,YY)
C2=(EPS0*AJ(0)*IB(0)-AJ(1)*IB(1)+RHO0*FJM/SIGMA)*YY
XX=KJ(NCOL-1)*DX(NCOL-1)/2.D0
CALL E2(XX,YY)
C3=(AJ(NCOL)*IB(NCOL)-2.D0*AJ(NCOL-1)*IB(NCOL-1)+AJ(NCOL-2)*IB(NCOL-2))*YY
C4=0.D0
DO MCOL=2,NCOL-2
XX=KJ(NCOL-1)*DX(NCOL-1)/2.D0+INTXPKS(MCOL,NCOL-2)
CALL E2(XX,YY)
C4=C4+(AJ(MCOL-1)*IB(MCOL-1)-AJ(MCOL)*IB(MCOL))*YY
END DO
QJ(NCOL-1)=2.D0*SIGMA*KJ(NCOL-1)*(C1+C2+C3+C4)
!Q(XK)
DO ICOL=3,NCOL-2
XX=KJ(ICOL)*DX(ICOL)/2.D0+INTXPKS(1,ICOL-1)
CALL E2(XX,YY)
C1=(EPS0*AJ(0)*IB(0)+RHO0*FJM/SIGMA-AJ(1)*IB(1))*YY
XX=KJ(ICOL)*DX(ICOL)/2.D0+INTXPKS(ICOL+1,NCOL)
CALL E2(XX,YY)
C2=(EPSL*AJ(NCOL+1)*IB(NCOL+1)+RHOL*FJP/SIGMA-AJ(NCOL)*IB(NCOL))*YY
XX=KJ(ICOL)*DX(ICOL)/2.D0
CALL E2(XX,YY)
C3=(AJ(ICOL+1)*IB(ICOL+1)-2.D0*AJ(ICOL)*IB(ICOL)+AJ(ICOL-1)*IB(ICOL-1))*YY
C4=0.D0
DO MCOL=2,ICOL-1
XX=KJ(ICOL)*DX(ICOL)/2.D0+INTXPKS(MCOL,ICOL-1)
CALL E2(XX,YY)
C4=C4+(AJ(MCOL-1)*IB(MCOL-1)-AJ(MCOL)*IB(MCOL))*YY
END DO
C5=0.D0
DO MCOL=ICOL+1,NCOL-1
XX=KJ(ICOL)*DX(ICOL)/2.D0+INTXPKS(ICOL+1,MCOL)
CALL E2(XX,YY)
C5=C5+(AJ(MCOL+1)*IB(MCOL+1)-AJ(MCOL)*IB(MCOL))*YY
QJ(ICOL)=2.D0*SIGMA*KJ(ICOL)*(C1+C2+C3+C4+C5)
END DO
END DO
END SUBROUTINE CALC_FLUXPLUSQ
