MODULE ML1D_MOD
    INTEGER INU,NBNU
    PARAMETER(NBNU=2500)
    INTEGER NBBANDH,NBBAND !NUMBER OF GROUPS,K-VALUES,TEMPERATURE,COMPOSITION,SPECTRAL BANDS
    INTEGER IBAND,IBANDH
    PARAMETER(NBBANDH=449,NBBAND=449) !471) !NBBANDC BANDS WHERE CO2 ABSORBS,NBBAND TOTAL NUMBER OF NARROW BANDS
    DOUBLE PRECISION NBDAT(NBBAND),NBDATH(NBBANDH)
    INTEGER NUMEAN
    INTEGER NCOLMAX,NCOL,SCOL,KCOL,MCOL,NCASE !N::NUMBER OF ISOTHERMAL ELEMENTS
    INTEGER NXG,IXG,IX,DUMXC,DUMXH !NUMBER OF GAS COMPOSITION, ASSOCIATED INDEXES, COMPOSITION DINT INDEX
    INTEGER NTG,ITG,ITEMP,DUMTEMP !NUMBER OF GAS TEMPERATURES, ASSOCIATED INDEXES, TEMPERATURE DINT INDEX
    PARAMETER(NCOLMAX=1001)
    PARAMETER(NTG=48)
    PARAMETER(NXG=7)
    INTEGER IXH
    DOUBLE PRECISION DX(NCOLMAX),XC(NCOLMAX),XH(NCOLMAX),X(NCOLMAX),TEMP(0:NCOLMAX+1),PRESS(NCOLMAX) !LENGTH,MOLAR FRACTION,TEMPERATURE,PRESSURE
    DOUBLE PRECISION AJ(0:NCOLMAX+1) !LOCAL WEIGHTS
    DOUBLE PRECISION NULOC(NBNU),KLOC(NBNU,NTG,NXG),KHH
    DOUBLE PRECISION KJ(NCOLMAX),KJC(NCOLMAX),KJH(NCOLMAX),KJCTEMP1,KJCTEMP2,KJHTEMP1,KJHTEMP2 !LOCAL ABSORPTION COEFFICIENT
    DOUBLE PRECISION IB(0:NCOLMAX+1),IBN(0:NCOLMAX+1) !LOCAL BLACKBODY INTENSITY (EVALUATED HERE AS THE FORTH POWER OF THE LOCAL TEMPERATURE)
    DOUBLE PRECISION EPS0,EPSL !EMISSIVITIES OF WALLS
    DOUBLE PRECISION RHO0,RHOL !REFLECTIVITIES OF WALLS
    DOUBLE PRECISION FJP !DIRECTIONNAL WALLS FLUX (ON THE RIGHT)
    DOUBLE PRECISION FJM !DIRECTIONNAL WALLS FLUX (ON THE LEFT)
    DOUBLE PRECISION QJ(NCOLMAX) !LOCAL DIVERGENCE OF THE RADIATIVE FLUX
    DOUBLE PRECISION INTXPKS(NCOLMAX,NCOLMAX) !INTEGRALS OF XPS*DX BETWEEN TWO POINTS INSIDE THE GASEOUS MEDIUM
    DOUBLE PRECISION FP0,FPL,FPT,FNTC3,FPTC3 !TOTAL DIRECTIONAL FLUX
    DOUBLE PRECISION TESTE3,FNTTEST,FPTTEST
    DOUBLE PRECISION FN0,FNL,FNT !TOTAL DIRECTIONAL FLUX
    DOUBLE PRECISION SIGMA,PI,CR2,DNU
    PARAMETER(SIGMA=5.67D-8,PI=4.D0*DATAN(1.D0),CR2=1.4388D0,DNU=0.01D0)
    DOUBLE PRECISION EPSGI,LL
    CHARACTER*200 INFILE(NBBANDH)
    INTEGER INFILE_CLASSES(NBBANDH)

    !!! TMP
    INTEGER li,lj,lk,lg;

    !!!MSCK
    INTEGER NBGROUP,NKMAX !NUMBER OF GROUPS,K-VALUES
    INTEGER IGROUP,IK
    ! PARAMETER (NBGROUP=32,NKMAX=15)
    PARAMETER (NKMAX=15)
    INTEGER ITREF,IXREF
    PARAMETER(ITREF=NTG,IXREF=2) !INDEX OF THE REFERENCE STATE::TEMPERATURE IS THE HIGHEST ONE, COMPOSITION

    ! DOUBLE PRECISION GREF(NBBAND,NBGROUP,NKMAX) !VALUES OF g IN THE REFERENCE STATE  
    DOUBLE PRECISION,ALLOCATABLE  ::  GREF(:,:,:)      

    ! DOUBLE PRECISION KG(NKMAX,NBGROUP,NTG,NXG),WG(NBGROUP) !K-VALUES (UNDER THE CORRELATED-K ASSUMPTION)
    DOUBLE PRECISION,ALLOCATABLE  ::  KG(:,:,:,:), WG(:)

    ! DOUBLE PRECISION KMSCKLOC(NKMAX,NBGROUP,NTG,NXG),DNUMSCK(NBGROUP,NKMAX) 
    DOUBLE PRECISION,ALLOCATABLE :: KMSCKLOC(:,:,:,:),DNUMSCK(:,:)


    ! !!!MSCK
    ! INTEGER NBGROUP,NKMAX !NUMBER OF GROUPS,K-VALUES
    ! INTEGER IGROUP,IK
    ! PARAMETER (NBGROUP=32,NKMAX=15)
    ! INTEGER ITREF,IXREF
    ! PARAMETER(ITREF=NTG,IXREF=2) !INDEX OF THE REFERENCE STATE::TEMPERATURE IS THE HIGHEST ONE, COMPOSITION
    ! DOUBLE PRECISION GREF(NBBAND,NBGROUP,NKMAX) !VALUES OF g IN THE REFERENCE STATE     
    ! DOUBLE PRECISION KG(NKMAX,NBGROUP,NTG,NXG),WG(NBGROUP) !K-VALUES (UNDER THE CORRELATED-K ASSUMPTION)
    ! DOUBLE PRECISION KMSCKLOC(NKMAX,NBGROUP,NTG,NXG),DNUMSCK(NBGROUP,NKMAX)


    INTEGER NKMAX1,NBGROUP1
    DOUBLE PRECISION F0MT,F0PT,FN0T,FP0T,FNLT,FPLT,FJPT,FJMT,QJT(NCOLMAX)
    INTEGER ICOL,JCOL
END MODULE ML1D_MOD

PROGRAM MAIN
    USE ML1D_MOD
    IMPLICIT NONE
    DOUBLE PRECISION L
    !!LBL DATA
    DOUBLE PRECISION L0,DUM,NUCMAX
    DOUBLE PRECISION KC(NBNU,NTG,1:NXG),KH(NBNU,NTG,1:NXG),TEMPS(NTG) !TEMPERATURE OF SPECTRUMS
    DOUBLE PRECISION A0M,A0P,XXXX,YYYY
    DOUBLE PRECISION IBT0,IBTL,NU

    !READ INPUTS FOR THE CALCULATION
    OPEN(1,FILE='CASE')
        READ(1,*) NCASE
        READ(1,*) NCOL
    CLOSE(1)
    CALL CASEGEN
    CALL INIT
    CALL LOAD_CLASSES




    !!
    OPEN(3,FILE='WVNB.DAT')
        DO IBAND=1,NBBAND
            READ(3,*) NBDAT(IBAND)
        END DO
    CLOSE(3)
    OPEN(21,FILE='WVNBH.DAT')
        DO IBAND=1,NBBANDH
            READ(21,*) NBDATH(IBAND)
        END DO
    CLOSE(21)
    !!
    DO ICOL=0,NCOL+1
        IB(ICOL)=0.D0
        DO INU=1,NBNU*NBBAND
            NU=NBDAT(1)-12.5D0+DBLE(INU-1)*DNU
            IB(ICOL)=IB(ICOL)+0.11907D-7*(NU)**3.D0/(DEXP(CR2*(NU)/TEMP(ICOL))-1.D0)*DNU
        ENDDO
        IBN(ICOL)=(PI*IB(ICOL)/SIGMA)**(1.D0/4.D0)
        IB(ICOL)=IBN(ICOL)**4.D0
    END DO

    !!LOOP OVER BANDS
    DO IBAND=1,NBBAND
        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        NUMEAN=NBDAT(IBAND)
        WRITE(*,*) IBAND,NBBAND




        NBGROUP = INFILE_CLASSES(IBAND-1)
        ! print *, "NBGROUP", NBGROUP

        
        ALLOCATE(GREF(NBBAND, NBGROUP, NKMAX))
        DO li=1,NBBAND
            DO lj=1, NBGROUP
                DO lk=1, NKMAX
                    GREF(li,lj,lk)=0
                END DO
            END DO
        END DO
    
        ALLOCATE(KG(NKMAX, NBGROUP, NTG, NXG))
        DO li=1,NKMAX
            DO lj=1, NBGROUP
                DO lk=1, NTG
                    DO lg=1, NXG
                        KG(li,lj,lk,lg)=0
                    END DO
                END DO
            END DO
        END DO

        ALLOCATE(WG(NBGROUP))
        DO li=1,NBGROUP
            WG(li)=0
        END DO
    
        ALLOCATE(KMSCKLOC(NKMAX,NBGROUP,NTG,NXG))
        DO li=1,NKMAX
            DO lj=1, NBGROUP
                DO lk=1, NTG
                    DO lg=1, NXG
                        KMSCKLOC(li,lj,lk,lg)=0
                    END DO
                END DO
            END DO
        END DO

        ALLOCATE(DNUMSCK(NBGROUP, NKMAX))
        DO li=1,NBGROUP
            DO lj=1, NKMAX
                DNUMSCK(li,lj)=0
            END DO
        END DO
        ! DO IBANDH=1,NBBANDH
        !     IF(NBDATH(IBANDH).EQ.NBDAT(IBAND)) THEN
        !         ! print *, "GREF(IBANDH,1,１):", GREF(IBANDH,1,1)
        !         DO IGROUP=1,NBGROUP
        !             DO IK=1,NKMAX-1
        !                 GREF(IBANDH,IGROUP,IK) = 0
        !                 ! print *, "GREF(IBANDH,IGROUP,IK):", GREF(IBANDH,IGROUP,IK)
        !                 ! GREF()
        !             END DO
        !         END DO
        !     END IF
        ! END DO





        !!MSCK::DO INU=1,NBNU
        DO IGROUP=1,NBGROUP
            DO IK=1,NKMAX
                !!NULOC(INU)=NBDAT(IBAND)-12.5D0+DBLE(INU-1)*DNU
                DNUMSCK(IGROUP,IK)=DBLE(NBNU)*DNU
                DO ITG=1,NTG
                    DO IXG=1,NXG
                        KMSCKLOC(IK,IGROUP,ITG,IXG)=0.D0
                    END DO
                END DO
            END DO
        END DO
        NBGROUP1=1
        NKMAX1=1
        !!
        DO IBANDH=1,NBBANDH
            IF(NBDATH(IBANDH).EQ.NBDAT(IBAND)) THEN
                CALL LECT_MSCKH(IBANDH)
                NBGROUP1=NBGROUP
                NKMAX1=NKMAX-1
                DO IGROUP=1,NBGROUP
                    DO IK=1,NKMAX-1
                        DNUMSCK(IGROUP,IK)=DBLE(NBNU)*DNU*(GREF(IBANDH,IGROUP,IK+1)-GREF(IBANDH,IGROUP,IK))*WG(IGROUP)
                    END DO
                END DO
            END IF
        END DO
        !!
        !LOOP OVER WAVENUMBERS INSIDE A BAND
        !!MSCK::DO INU=1,NBNU
        DO IGROUP=1,NBGROUP1
            DO IK=1,NKMAX1
                !!EVALUATE ABSORPTION COEFFICIENTS AND WEIGHTS
                DO ICOL=1,NCOL
                    X(ICOL)=XH(ICOL)
                    CALL KHINT(TEMP(ICOL),XH(ICOL),KHH)
                    KJH(ICOL)=XH(ICOL)*PRESS(ICOL)*KHH
                    KJ(ICOL)=KJH(ICOL)
                    AJ(ICOL)=PI/SIGMA/IBN(ICOL)**4.D0*0.11907D-7*NUMEAN**3.D0/(DEXP(CR2*NUMEAN/TEMP(ICOL))-1.D0)*DNUMSCK(IGROUP,IK)
                END DO
                !GRAY GAS AND WALLS
                !WALLS
                AJ(0)=PI/SIGMA/IBN(0)**4.D0*0.11907D-7*NUMEAN**3.D0/(DEXP(CR2*NUMEAN/TEMP(0))-1.D0)*DNUMSCK(IGROUP,IK)
                IB(0)=IBN(0)**4.D0
                AJ(NCOL+1)=PI/SIGMA/IBN(NCOL+1)**4.D0*0.11907D-7*NUMEAN**3.D0/&
                    &(DEXP(CR2*NUMEAN/TEMP(NCOL+1))-1.D0)*DNUMSCK(IGROUP,IK)
                IB(NCOL+1)=IBN(NCOL+1)**4.D0
                CALL CALC_FLUXPLUSQ
                FJMT=FJMT+FJM
                FJPT=FJPT+FJP
                FNT=FNT+FP0-FN0
                FPT=FPT+FPL-FNL
                DO ICOL=1,NCOL
                    QJT(ICOL)=QJT(ICOL)+QJ(ICOL)
                END DO
                !MSCK::END LOOP OVER WAVENUMBERS
            END DO
        END DO
            
            
        DEALLOCATE(GREF)
        DEALLOCATE(KG)
        DEALLOCATE(WG)
        DEALLOCATE(KMSCKLOC)
        DEALLOCATE(DNUMSCK)


        !END LOOP OVER BANDS
    END DO
    !OUTPUT
    IBT0=0.D0
    IBTL=0.D0
    DO INU=1,NBNU*NBBAND
        NU=NBDAT(1)-12.5D0+DBLE(INU-1)*DNU
        IBT0=IBT0+0.11907D-7*(NU)**3.D0/(DEXP(CR2*(NU)/TEMP(0))-1.D0)*DNU
        IBTL=IBTL+0.11907D-7*(NU)**3.D0/(DEXP(CR2*(NU)/TEMP(NCOL+1))-1.D0)*DNU
    ENDDO
    !FNT=FNT+FP0-FN0
    !FPT=FPT+FPL-FNL
    FNT=EPS0*(PI*IBT0)-EPS0*FJMT
    FPT=EPSL*FJPT-EPSL*(PI*IBTL)


    ! OPEN(1,FILE='MSCK25_OUTPUT_FLUX-NEW.DAT') !IN W/M2
    ! OPEN(2,FILE='MSCK25_OUTPUT_Q-NEW.DAT')    !IN kW/M3
    ! WRITE(1,*) FJMT,FJPT
    ! WRITE(1,*) FNT,FPT

    !! ZZ
    print *,FJMT, FJPT
    print *,FNT, FPT !! PRINT FNT
    !!

    L=DX(1)/2.D0
    ! WRITE(2,*) L,QJT(1)/10.D0 !HERE ABSORPTION COEFFICIENTS ARE IN CM-1 AND DISTANCES IN CM !/(sigma*temp(1)**4.d0*kj(1))
    DO ICOL=2,NCOL
        L=L+(DX(ICOL-1)+DX(ICOL))/2.D0
        ! WRITE(2,*) L,QJT(ICOL)/10.D0 
    END DO
    ! CLOSE(1)
END
