
!! 读取各个文件的分类数目
SUBROUTINE LOAD_CLASSES
    USE ML1D_MOD
    IMPLICIT NONE
    INTEGER :: j
    
    OPEN(1, FILE='../../../../MSCK25-DATA-NEW-HUANGSIYUAN/H2O.classes')   
        READ(1, *) INFILE_CLASSES
        do j=1, NBBAND
            print *, INFILE_CLASSES(j)
        end do
    CLOSE(1)
END SUBROUTINE LOAD_CLASSES


    SUBROUTINE LECT_MSCKH(JBAND)
    USE ML1D_MOD
    IMPLICIT NONE
    INTEGER JBAND
    NUMEAN=NBDATH(JBAND)
	IF(NUMEAN.LT.100) WRITE(INFILE(JBAND),200) NUMEAN
    IF(NUMEAN.GE.100.AND.NUMEAN.LT.1000) WRITE(INFILE(JBAND),201) NUMEAN
    IF(NUMEAN.GE.1000.AND.NUMEAN.LT.10000) WRITE(INFILE(JBAND),202) NUMEAN
	IF(NUMEAN.GE.10000) WRITE(INFILE(JBAND),203) NUMEAN
200 FORMAT('../../../../MSCK25-DATA-NEW-HUANGSIYUAN/H2O/MSCK_H2O_',I2,'CM_1')    
201 FORMAT('../../../../MSCK25-DATA-NEW-HUANGSIYUAN/H2O/MSCK_H2O_',I3,'CM_1')    
202 FORMAT('../../../../MSCK25-DATA-NEW-HUANGSIYUAN/H2O/MSCK_H2O_',I4,'CM_1')    
203 FORMAT('../../../../MSCK25-DATA-NEW-HUANGSIYUAN/H2O/MSCK_H2O_',I5,'CM_1')    
102 FORMAT(100(E20.10,1X))   

	OPEN(1,FILE=INFILE(JBAND))
    ! NBGROUP GREATER
	DO IGROUP=1,NBGROUP !LOOP OVER GROUPS
        ! print *, "IGROUP", IGROUP
	    READ(1,102) WG(IGROUP),(GREF(JBAND,IGROUP,IK),IK=1,NKMAX)
        DO ITG=1,NTG !LOOP OVER TEMPERATURE
            DO IXG=1,NXG !LOOP OVER COMPOSITION
                READ(1,102) (KMSCKLOC(IK,IGROUP,ITG,IXG),IK=1,NKMAX)
            END DO !END LOOP OVER COMPOSITION
        END DO !END LOOP OVER TEMPERATURE
	END DO !END LOOP OVER GROUPS
	CLOSE(1)
    END SUBROUTINE LECT_MSCKH
    
    SUBROUTINE LECT_B
    !READ NARROW BAND DATAS :: BAND CENTERS
    !CREATE CLUSTER FILENAMES
    USE ML1D_MOD
    IMPLICIT NONE
	OPEN(2,FILE='WVNB.DAT')
	DO IBAND=1,NBBAND
	READ(2,*) NBDAT(IBAND)
	END DO
	CLOSE(2)
	!END READ NARROW BAND CENTERS
    END SUBROUTINE LECT_B
 
  	SUBROUTINE KHINT(XTEMP,XX,K)
	USE ML1D_MOD
	IMPLICIT NONE
	DOUBLE PRECISION XTEMP,XX
	DOUBLE PRECISION DEX,X0,K1H,K2H,K,K11,K12,K21,K22
	ITEMP=DINT((XTEMP-300.D0)/100.D0)+1
	K=0.D0
	IXH=1
	X0=0.D0
	DEX=0.2D0
	!!
    IF(XX.LT.0.01D0) THEN
    K1H=KMSCKLOC(IK,IGROUP,ITEMP,1)+(KMSCKLOC(IK,IGROUP,ITEMP+1,1)-KMSCKLOC(IK,IGROUP,ITEMP,1))&
    &/100.D0*(XTEMP-(300.D0+DBLE(ITEMP-1)*100.D0))
    K2H=KMSCKLOC(IK+1,IGROUP,ITEMP,1)+(KMSCKLOC(IK+1,IGROUP,ITEMP+1,1)-KMSCKLOC(IK+1,IGROUP,ITEMP,1))&
    &/100.D0*(XTEMP-(300.D0+DBLE(ITEMP-1)*100.D0))
    K=DSQRT(K1H*K2H)
    END IF
    IF(XX.EQ.1.D0) THEN
    K1H=KMSCKLOC(IK,IGROUP,ITEMP,NXG)+(KMSCKLOC(IK,IGROUP,ITEMP+1,NXG)-KMSCKLOC(IK,IGROUP,ITEMP,NXG))&
    &/100.D0*(XTEMP-(300.D0+DBLE(ITEMP-1)*100.D0))
    K2H=KMSCKLOC(IK+1,IGROUP,ITEMP,NXG)+(KMSCKLOC(IK+1,IGROUP,ITEMP+1,NXG)-KMSCKLOC(IK+1,IGROUP,ITEMP,NXG))&
    &/100.D0*(XTEMP-(300.D0+DBLE(ITEMP-1)*100.D0))
    K=DSQRT(K1H*K2H)
    END IF
    IF(XX.GE.0.01D0.AND.XX.LT.0.1D0) THEN
    IXH=1
    DEX=0.09D0
    X0=0.01D0
    END IF
    IF(XX.GE.0.1D0.AND.XX.LT.0.2D0) THEN
    IXH=2
    DEX=0.1D0
    X0=0.1D0
    END IF
    IF(XX.GE.0.2D0.AND.XX.LT.0.4D0) THEN
    IXH=3
    X0=0.2D0
    END IF
    IF(XX.GE.0.4D0.AND.XX.LT.0.6D0) THEN
    IXH=4
    X0=0.4D0
    END IF
    IF(XX.GE.0.6D0.AND.XX.LT.0.8D0) THEN
    IXH=5
    X0=0.6D0
    END IF
    IF(XX.GE.0.8D0.AND.XX.LT.1.D0) THEN
    IXH=6
    X0=0.8D0
    END IF
    IF(K.EQ.0.D0) THEN
    K11=KMSCKLOC(IK,IGROUP,ITEMP,IXH)+(KMSCKLOC(IK,IGROUP,ITEMP+1,IXH)-KMSCKLOC(IK,IGROUP,ITEMP,IXH))&
    &/100.D0*(XTEMP-(300.D0+DBLE(ITEMP-1)*100.D0))
    K12=KMSCKLOC(IK,IGROUP,ITEMP,IXH+1)+(KMSCKLOC(IK,IGROUP,ITEMP+1,IXH+1)-KMSCKLOC(IK,IGROUP,ITEMP,IXH+1))&
    &/100.D0*(XTEMP-(300.D0+DBLE(ITEMP-1)*100.D0))
    K1H=K11+(K12-K11)*(XX-X0)/DEX
    K21=KMSCKLOC(IK+1,IGROUP,ITEMP,IXH)+(KMSCKLOC(IK+1,IGROUP,ITEMP+1,IXH)-KMSCKLOC(IK+1,IGROUP,ITEMP,IXH))&
    &/100.D0*(XTEMP-(300.D0+DBLE(ITEMP-1)*100.D0))
    K22=KMSCKLOC(IK+1,IGROUP,ITEMP,IXH+1)+(KMSCKLOC(IK+1,IGROUP,ITEMP+1,IXH+1)-KMSCKLOC(IK+1,IGROUP,ITEMP,IXH+1))&
    &/100.D0*(XTEMP-(300.D0+DBLE(ITEMP-1)*100.D0))
    K2H=K21+(K22-K21)*(XX-X0)/DEX
    K=DSQRT(K1H*K2H)
    END IF
    END SUBROUTINE KHINT

SUBROUTINE E1(XX,YY)
IMPLICIT NONE
DOUBLE PRECISION XX,YY
IF(XX.LE.1) THEN
YY=-DLOG(XX)-0.57721566D0+0.99999193D0*XX-0.24991055D0*XX*XX+0.05519968D0*XX**3.D0-0.00976004D0*XX**4.D0+0.00107857D0*XX**5.D0
ELSE
YY=DEXP(-XX)/XX*(XX*XX+2.334733D0*XX+.250621D0)/(XX*XX+3.330657D0*XX+1.681534D0)
END IF
RETURN
END

SUBROUTINE E2(XX,YY)
IMPLICIT NONE
DOUBLE PRECISION XX,YY
CALL E1(XX,YY)
YY=(DEXP(-XX)-XX*YY)
IF(XX.EQ.0.D0) YY=1.D0
RETURN
END

SUBROUTINE E3(XX,YY)
IMPLICIT NONE
DOUBLE PRECISION XX,YY
CALL E1(XX,YY)
YY=(DEXP(-XX)-XX*YY)
YY=0.5D0*(DEXP(-XX)-XX*YY)
IF(XX.EQ.0.D0) YY=.5D0
RETURN
END

SUBROUTINE CASEGEN
USE ML1D_MOD
IMPLICIT NONE
DOUBLE PRECISION TW,TC,E
DOUBLE PRECISION DDX(NCOL)
character(len=10) :: param
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    CASE 1: CASE OF FIGURE 4.15 IN DENISSON'S DISSERTATION       !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
IF(NCASE.EQ.1) THEN 
LL=100.D0
DO ICOL=1,NCOL
DX(ICOL)=(LL)/DBLE(NCOL)
TEMP(ICOL)= 1500.D0 
XH(ICOL)=.5D0
XC(ICOL)=0.D0
PRESS(ICOL)=1.D0
ENDDO
TEMP(0)=1200.D0
TEMP(NCOL+1)=600.D0
EPS0=0.6D0
EPSL=0.6D0
RHO0=1.D0-EPS0
RHOL=1.D0-EPSL
END IF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    CASE 2: CASE OF FIGURE 3.10 IN DENISSON'S DISSERTATION       !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
IF(NCASE.EQ.2) THEN 
LL=200.D0
TC=1000.D0 !AVERAGE TEMPERATURE
TW=1500.D0 !TO ALLOW DT=(TW-TC)/2=250
DO ICOL=1,NCOL
DX(ICOL)=(LL)/DBLE(NCOL)
TEMP(ICOL)= TC+(TW-TC)/2.D0*DCOS(PI*(DBLE(ICOL)/DBLE(NCOL+1)))
XH(ICOL)=.1D0
XC(ICOL)=0.D0
PRESS(ICOL)=1.D0
ENDDO
TEMP(0)=1250.D0
TEMP(NCOL+1)=750.D0
EPS0=1.D0
EPSL=1.D0
RHO0=1.D0-EPS0
RHOL=1.D0-EPSL
END IF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    CASE 3: CASE OF FIGURE 3.11 IN DENISSON'S DISSERTATION       !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
IF(NCASE.EQ.3) THEN 
LL=200.D0
TC=1000.D0 !AVERAGE TEMPERATURE
TW=2000.D0 !TO ALLOW DT=(TW-TC)/2=500
DO ICOL=1,NCOL
DX(ICOL)=(LL)/DBLE(NCOL)
TEMP(ICOL)= TC+(TW-TC)/2.D0*DCOS(PI*(DBLE(ICOL)/DBLE(NCOL+1)))
XH(ICOL)=.1D0
XC(ICOL)=0.D0
PRESS(ICOL)=1.D0
ENDDO
TEMP(0)=1500.D0
TEMP(NCOL+1)=500.D0
EPS0=1.D0
EPSL=1.D0
RHO0=1.D0-EPS0
RHOL=1.D0-EPSL
END IF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    CASE 4: CASE 3 IN CHU et al IJHMT2011 (Vol. 54, pp 4736-4745)!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
IF(NCASE.EQ.4) THEN 
LL=100.D0
TC=1000.D0 !AVERAGE TEMPERATURE
TW=0.D0 !NOT USED HERE
DO ICOL=1,NCOL
DX(ICOL)=(LL)/DBLE(NCOL)
TEMP(ICOL)=TC 
XH(ICOL)=4.D0*(1.D0-DBLE(ICOL)/DBLE(NCOL+1))*DBLE(ICOL)/DBLE(NCOL+1)
XC(ICOL)=0.D0
PRESS(ICOL)=1.D0
ENDDO
TEMP(0)=300.D0
TEMP(NCOL+1)=300.D0
EPS0=1.D0
EPSL=1.D0
RHO0=1.D0-EPS0
RHOL=1.D0-EPSL
END IF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    CASE 5: from CASE 4 IN CHU et al                             !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
IF(NCASE.EQ.5) THEN 
LL=20.D0
TC=1500.D0 
TW=300.D0 
DO ICOL=1,NCOL
DX(ICOL)=(LL)/DBLE(NCOL)
TEMP(ICOL)=TW+(TC-TW)*DEXP(-TC/(TC-TW)/4.D0*LL*DBLE(ICOL)/DBLE(NCOL+1)*2.D0) 
XH(ICOL)=1.D0
XC(ICOL)=0.D0
PRESS(ICOL)=1.D0
ENDDO
TEMP(0)=TC
TEMP(NCOL+1)=TW
EPS0=1.D0
EPSL=1.D0
RHO0=1.D0-EPS0
RHOL=1.D0-EPSL
END IF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    CASE 6: FIGS 3-9 IN PIERROT JQSRT1999 pp 523-548                !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
IF(NCASE.EQ.6) THEN 
LL=1000.D0
TC=500.D0 
TW=2500.D0 
DO ICOL=1,NCOL
DX(ICOL)=(LL)/DBLE(NCOL)
TEMP(ICOL)=TC+4.D0*(TW-TC)*(DBLE(ICOL)/DBLE(NCOL+1)-.5D0)**2.D0
XH(ICOL)=.1D0
XC(ICOL)=0.D0
PRESS(ICOL)=1.D0
ENDDO
TEMP(0)=TW
TEMP(NCOL+1)=TW
EPS0=1.D0
EPSL=1.D0
RHO0=1.D0-EPS0
RHOL=1.D0-EPSL
END IF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    CASE 7: FIG 5 IN PIERROT JQSRT1999 pp 523-548                !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
IF(NCASE.EQ.7) THEN 
LL=100.D0
TC=2500.D0 
TW=500.D0 
DO ICOL=1,NCOL
DX(ICOL)=(LL)/DBLE(NCOL)
TEMP(ICOL)=TC+4.D0*(TW-TC)*(DBLE(ICOL)/DBLE(NCOL+1)-.5D0)**2.D0
XH(ICOL)=.1D0
XC(ICOL)=0.D0
PRESS(ICOL)=1.D0
ENDDO
TEMP(0)=TW
TEMP(NCOL+1)=TW
EPS0=1.D0
EPSL=1.D0
RHO0=1.D0-EPS0
RHOL=1.D0-EPSL
END IF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    CASE 8: FIG 6.3 IN DENISSON'S DISSERTATION                   !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
IF(NCASE.EQ.8) THEN 
LL=10.D0
TC=1250.D0 
TW=0.D0 !NOT USED HERE
DO ICOL=1,NCOL
DX(ICOL)=(LL)/DBLE(NCOL)
TEMP(ICOL)=TC
XH(ICOL)=0.4D0
XC(ICOL)=0.2D0
PRESS(ICOL)=1.D0
ENDDO
TEMP(0)=400.D0
TEMP(NCOL+1)=1500.D0
EPS0=.8D0
EPSL=.8D0
RHO0=1.D0-EPS0
RHOL=1.D0-EPSL
END IF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    CASE 9: FIG 6.6(B) IN DENISSON'S DISSERTATION                !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
IF(NCASE.EQ.9) THEN 
LL=1000.D0
TC=1000.D0 
TW=2000.D0 !TO ALLOW DT=(TW-TC)/2=500
DO ICOL=1,NCOL
DX(ICOL)=(LL)/DBLE(NCOL)
TEMP(ICOL)=TC+(TW-TC)/2.D0*DCOS(2.D0*PI*(DBLE(ICOL)/DBLE(NCOL+1)))
XH(ICOL)=0.5D0-0.5D0*DCOS(PI*(DBLE(ICOL)/DBLE(NCOL+1)))
XC(ICOL)=0.5D0+0.5D0*DCOS(PI*(DBLE(ICOL)/DBLE(NCOL+1)))
PRESS(ICOL)=1.D0
ENDDO
TEMP(0)=1500.D0
TEMP(NCOL+1)=1500.D0
EPS0=1.D0
EPSL=1.D0
RHO0=1.D0-EPS0
RHOL=1.D0-EPSL
END IF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    CASE 10: NEW                                                 !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
IF(NCASE.EQ.10) THEN 
LL=100.D0
TC=1500.D0 
TW=300.D0 
DO ICOL=1,NCOL
DX(ICOL)=(LL)/DBLE(NCOL)
IF(DBLE(ICOL)/DBLE(NCOL+1).LE.0.5D0) TEMP(ICOL)=TC
IF(DBLE(ICOL)/DBLE(NCOL+1).GT.0.5D0) TEMP(ICOL)=TW
XH(ICOL)=0.5D0
XC(ICOL)=0.D0
PRESS(ICOL)=1.D0
ENDDO
TEMP(0)=TC
TEMP(NCOL+1)=TW
EPS0=1.D0
EPSL=1.D0
RHO0=1.D0-EPS0
RHOL=1.D0-EPSL
END IF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    CASE 11: FIG. 4.7 PIERROT                                    !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
IF(NCASE.EQ.11) THEN 
! LL=20.D0
CALL get_command_argument(1, param)
read(param, *),LL
print *, "LL:", LL
TC=2500.D0 
TW=500.D0 
E=10.D0

DX(1)=DBLE(LL-E)/2.D0
DX(NCOL)=DBLE(LL-E)/2.D0
DDX(1)=DX(1)
DDX(NCOL)=LL
DO ICOL=2,NCOL-1
DX(ICOL)=E/DBLE(NCOL-2)
DDX(ICOL)=DDX(ICOL-1)+DX(ICOL)
ENDDO
DO ICOL=1,NCOL
IF(DABS(DDX(ICOL)-LL/2.D0).LE.E/2.D0) THEN
TEMP(ICOL)=TC-(TC-TW)*DABS(DDX(ICOL)/LL-.5D0)*2.D0*LL/E
ELSE
TEMP(ICOL)=TW
END IF
XH(ICOL)=0.1D0
XC(ICOL)=0.D0
PRESS(ICOL)=1.D0
ENDDO
TEMP(0)=TW
TEMP(NCOL+1)=TW
EPS0=1.D0
EPSL=1.D0
RHO0=1.D0-EPS0
RHOL=1.D0-EPSL
END IF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    CASE 12: FIG 8 IN PIERROT JQSRT1999 pp 523-548                !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
IF(NCASE.EQ.12) THEN 
LL=20.D0
TC=500.D0 
TW=2500.D0 
DO ICOL=1,NCOL
DX(ICOL)=(LL)/DBLE(NCOL)
TEMP(ICOL)=TC+4.D0*(TW-TC)*(DBLE(ICOL)/DBLE(NCOL+1)-.5D0)**2.D0
XH(ICOL)=.1D0
XC(ICOL)=0.D0
PRESS(ICOL)=1.D0
ENDDO
TEMP(0)=TW
TEMP(NCOL+1)=TW
EPS0=0.2d0
EPSL=0.2d0
RHO0=1.D0-EPS0
RHOL=1.D0-EPSL
END IF


END SUBROUTINE CASEGEN


SUBROUTINE INIT
USE ML1D_MOD
IMPLICIT NONE
FJPT=0.D0
FJMT=0.D0
FNT=0.D0
FP0=0.D0
FN0=0.D0
FPL=0.D0
FNL=0.D0
FPT=0.D0
FN0T=0.D0
FP0T=0.D0
FNLT=0.D0
FPLT=0.D0
DO ICOL=1,NCOL
QJT(ICOL)=0.D0
END DO
DO ICOL=0,NCOL+1
IB(ICOL)=0.D0
END DO
END SUBROUTINE INIT