    SUBROUTINE LECT_C
    !READ NARROW BAND DATAS :: BAND CENTERS
    !CREATE CLUSTER FILENAMES
    USE MSCK_H2O
    IMPLICIT NONE
	OPEN(2,FILE='WVNB.DAT')
	DO IBAND=1,NBBAND
	READ(2,*) NBDAT(IBAND)
	NUMEAN=NBDAT(IBAND)
	IF(NUMEAN.LT.100) WRITE(INFILE(IBAND),200) NUMEAN
    IF(NUMEAN.GE.100.AND.NUMEAN.LT.1000) WRITE(INFILE(IBAND),201) NUMEAN
    IF(NUMEAN.GE.1000.AND.NUMEAN.LT.10000) WRITE(INFILE(IBAND),202) NUMEAN
	IF(NUMEAN.GE.10000) WRITE(INFILE(IBAND),203) NUMEAN
200 FORMAT('../../../../NEW CLUST 27T 25C FOR HUANGSIYUAN/H2O/H2O_CLUST_',I2,'CM_1_27T_25C')    
201 FORMAT('../../../../NEW CLUST 27T 25C FOR HUANGSIYUAN/H2O/H2O_CLUST_',I3,'CM_1_27T_25C')    
202 FORMAT('../../../../NEW CLUST 27T 25C FOR HUANGSIYUAN/H2O/H2O_CLUST_',I4,'CM_1_27T_25C')    
203 FORMAT('../../../../NEW CLUST 27T 25C FOR HUANGSIYUAN/H2O/H2O_CLUST_',I5,'CM_1_27T_25C')
    DO IXG=1,NXG    
    IF(NUMEAN.LT.100) WRITE(XINFILE(IBAND,IXG),210) IXG,NUMEAN,IXG    
    IF(NUMEAN.GE.100.AND.NUMEAN.LT.1000) WRITE(XINFILE(IBAND,IXG),211) IXG,NUMEAN,IXG
    IF(NUMEAN.GE.1000.AND.NUMEAN.LT.10000) WRITE(XINFILE(IBAND,IXG),212) IXG,NUMEAN,IXG
    IF(NUMEAN.GE.10000) WRITE(XINFILE(IBAND,IXG),213) IXG,NUMEAN,IXG
210 FORMAT('../../../../SPLITT_DATA/XH',I1,'/H2O_SPLITT_',I2,'CM_1_XH',I1)
211 FORMAT('../../../../SPLITT_DATA/XH',I1,'/H2O_SPLITT_',I3,'CM_1_XH',I1)    
212 FORMAT('../../../../SPLITT_DATA/XH',I1,'/H2O_SPLITT_',I4,'CM_1_XH',I1)
213 FORMAT('../../../../SPLITT_DATA/XH',I1,'/H2O_SPLITT_',I5,'CM_1_XH',I1)    
    END DO
	END DO
	CLOSE(2)
	!END READ NARROW BAND CENTERS
    END SUBROUTINE LECT_C
    
    SUBROUTINE LECT_CDATA(JBAND)
    !READ CLUSTER DATA
	USE MSCK_H2O
	IMPLICIT NONE
	INTEGER JBAND
	NUMEAN=NBDAT(JBAND)
	WRITE(*,*) NUMEAN
	OPEN(1000,FILE=INFILE(JBAND))
	DO INU=1,NBNU
    READ(1000,110) NULOC(INU),(KLOC(INU,ITG,1),ITG=1,NTG),GROUPINDEX(INU)
110 FORMAT(49(E20.10,1X),I3)
	ENDDO
	DO IXG=1,NXG
	OPEN(1001,FILE=XINFILE(JBAND,IXG))
	DO INU=1,NBNU
	READ(1001,110) NULOC(INU),(KLOC(INU,ITG,IXG),ITG=1,NTG)
	END DO
	CLOSE(1001)
	END DO
	END SUBROUTINE LECT_CDATA
	
	SUBROUTINE DELTACALC
	USE MSCK_H2O
	IMPLICIT NONE
    INTEGER INDEX
    !INIT
    DO INU=1,NBNU
    DO IGROUP=1,NBGROUP
    DELTA(IGROUP,INU)=0.D0
    END DO
    END DO
    !DELTA CALC
    DO INU=1,NBNU
    INDEX=GROUPINDEX(INU)
    DELTA(INDEX,INU)=1.D0
    END DO
    !END DELTA CALC
    END SUBROUTINE DELTACALC

    SUBROUTINE KMINMAX
	USE MSCK_H2O
	IMPLICIT NONE    
    DO IGROUP=1,NBGROUP
    KMIN(IGROUP)=1.D20
    KMAX(IGROUP)=-1.D0
    DO INU=1,NBNU
    IF(KLOC(INU,ITREF,IXREF).LE.KMIN(IGROUP).AND.GROUPINDEX(INU).EQ.IGROUP) KMIN(IGROUP)=KLOC(INU,ITREF,IXREF)
    IF(KLOC(INU,ITREF,IXREF).GE.KMAX(IGROUP).AND.GROUPINDEX(INU).EQ.IGROUP) KMAX(IGROUP)=KLOC(INU,ITREF,IXREF)
    END DO
    END DO
    END SUBROUTINE KMINMAX

    SUBROUTINE CLUSTERSIZE
	USE MSCK_H2O
	IMPLICIT NONE    
    DO IGROUP=1,NBGROUP
    SIZEGROUP(IGROUP)=0.D0
    END DO
    DO IGROUP=1,NBGROUP
    DO INU=1,NBNU
    SIZEGROUP(IGROUP)=SIZEGROUP(IGROUP)+DELTA(IGROUP,INU)
    END DO
    END DO
    END SUBROUTINE CLUSTERSIZE

    SUBROUTINE INDEXX(N,ARR,INDX)
    INTEGER N,INDX(N),M,NSTACK
    DOUBLE PRECISION ARR(N)
    PARAMETER (M=7,NSTACK=50)
    !INDEXES AN ARRAY ARR(1:N), I.E., OUTPUTS THE ARRAY INDX(1:N) SUCH THAT ARR(INDX(J))
    !IS IN ASCENDING ORDER FOR J = 1;2; : : :;N. THE INPUT QUANTITIES N AND ARR ARE NOT CHANGED.
    INTEGER I,INDXT,IR,ITEMP,J,JSTACK,K,L,ISTACK(NSTACK)
    DOUBLE PRECISION A
    DO  J=1,N
    INDX(J)=J
    ENDDO
    JSTACK=0
    L=1
    IR=N
    1 IF(IR-L.LT.M)THEN
    DO J=L+1,IR
    INDXT=INDX(J)
    A=ARR(INDXT)
    DO I=J-1,L,-1
    IF(ARR(INDX(I)).LE.A)GOTO 2
    INDX(I+1)=INDX(I)
    ENDDO 
    I=L-1
    2 INDX(I+1)=INDXT
    ENDDO
    IF(JSTACK.EQ.0)RETURN
    IR=ISTACK(JSTACK)
    L=ISTACK(JSTACK-1)
    JSTACK=JSTACK-2
    ELSE
    K=(L+IR)/2
    ITEMP=INDX(K)
    INDX(K)=INDX(L+1)
    INDX(L+1)=ITEMP
    IF(ARR(INDX(L)).GT.ARR(INDX(IR)))THEN
    ITEMP=INDX(L)
    INDX(L)=INDX(IR)
    INDX(IR)=ITEMP
    ENDIF
    IF(ARR(INDX(L+1)).GT.ARR(INDX(IR)))THEN
    ITEMP=INDX(L+1)
    INDX(L+1)=INDX(IR)
    INDX(IR)=ITEMP
    ENDIF
    IF(ARR(INDX(L)).GT.ARR(INDX(L+1)))THEN
    ITEMP=INDX(L)
    INDX(L)=INDX(L+1)
    INDX(L+1)=ITEMP
    ENDIF
    I=L+1
    J=IR
    INDXT=INDX(L+1)
    A=ARR(INDXT)
    3 CONTINUE
    I=I+1
    IF(ARR(INDX(I)).LT.A)GOTO 3
    4 CONTINUE
    J=J-1
    IF(ARR(INDX(J)).GT.A)GOTO 4
    IF(J.LT.I)GOTO 5
    ITEMP=INDX(I)
    INDX(I)=INDX(J)
    INDX(J)=ITEMP
    GOTO 3
    5 INDX(L+1)=INDX(J)
    INDX(J)=INDXT
    JSTACK=JSTACK+2
    IF(JSTACK.GT.NSTACK)PAUSE 'NSTACK TOO SMALL IN INDEXX'
    IF(IR-I+1.GE.J-L)THEN
    ISTACK(JSTACK)=IR
    ISTACK(JSTACK-1)=I
    IR=J-1
    ELSE
    ISTACK(JSTACK)=J-1
    ISTACK(JSTACK-1)=L
    L=I
    ENDIF
    ENDIF
    GOTO 1
    END SUBROUTINE INDEXX