    MODULE SPLITTER
	INTEGER NTG,ITG,ITEMP !NUMBER OF GAS TEMPERATURES, ASSOCIATED INDEXES
	PARAMETER(NTG=48)
	INTEGER NXG,IXG
	PARAMETER(NXG=7)
	INTEGER I,J,F,G,INU !INTEGER INDEXES
	INTEGER NBAND,IBAND !NUMBER OF NARROW BANDS AND ASSOCIATED INDEX
	PARAMETER(NBAND=449)
	INTEGER NNU,NNUB !TOTAL NUMBER OF SPECTRAL POINTS :: FS AND NARROW BAND
	PARAMETER(NNU=1490001,NNUB=2500) !(NNU=1499001,NNUB=2500)
	DOUBLE PRECISION TEMP !GAS TEMPERATURE
	DOUBLE PRECISION NUMIN(NBAND),NUMAX(NBAND) !SPECTRAL BAND BOUNDARIES 
	CHARACTER*100 OUTFILE(NBAND,NXG)
	INTEGER NUMFILE,IFILE !NUMBER OF OUTPUT FILES
	END MODULE SPLITTER 

	PROGRAM MAIN
	USE SPLITTER
	IMPLICIT NONE
	INTEGER NUMEAN
	DOUBLE PRECISION K(NNU,NTG),NU(NNU) !LBL ABSORPTION COEFFICIENT (FULL SPECTRUM)
	DOUBLE PRECISION KLOC(NNUB,NTG),NULOC(NNUB) !LBL ABSORPTION COEFFICIENT (OVER THE NARROW BAND)
	CHARACTER*200 INFILE !LBL DATAFILE
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	
!!  READ NARROW BAND BOUNDARIES
    OPEN(11,FILE='WAVENUMBER')
    DO IBAND=1,NBAND
    READ(11,*) NUMIN(IBAND),NUMAX(IBAND)
!   GENERATE OUTPUT FILE NAMES
    DO IXG=1,NXG    
    NUMEAN=DINT((NUMIN(IBAND)+NUMAX(IBAND))/2.D0)
    IF(NUMEAN.LT.100) WRITE(OUTFILE(IBAND,IXG),200) IXG,NUMEAN,IXG    
    IF(NUMEAN.GE.100.AND.NUMEAN.LT.1000) WRITE(OUTFILE(IBAND,IXG),201) IXG,NUMEAN,IXG
    IF(NUMEAN.GE.1000.AND.NUMEAN.LT.10000) WRITE(OUTFILE(IBAND,IXG),202) IXG,NUMEAN,IXG
    IF(NUMEAN.GE.10000) WRITE(OUTFILE(IBAND,IXG),203) IXG,NUMEAN,IXG
200 FORMAT('../../../../SPLITT_DATA/XH',I1,'/H2O_SPLITT_',I2,'CM_1_XH',I1)
201 FORMAT('../../../../SPLITT_DATA/XH',I1,'/H2O_SPLITT_',I3,'CM_1_XH',I1)    
202 FORMAT('../../../../SPLITT_DATA/XH',I1,'/H2O_SPLITT_',I4,'CM_1_XH',I1)
203 FORMAT('../../../../SPLITT_DATA/XH',I1,'/H2O_SPLITT_',I5,'CM_1_XH',I1)    
    END DO
    END DO
    CLOSE(11)
!!  READ REFERENCE LBL DATA
!   LOOP OVER COMPOSITION
    DO IXG=1,NXG
!   LOOP OVER TEMPERATURE    
    DO ITG=1,NTG
    TEMP=300.D0+DBLE(ITG-1)*100.D0
    ITEMP=DINT(TEMP)
	IF(ITEMP.LT.1000.D0.AND.IXG.EQ.1) WRITE(INFILE,101) ITEMP
	IF(ITEMP.GE.1000.D0.AND.IXG.EQ.1) WRITE(INFILE,102) ITEMP
101	FORMAT('../../../../LBL_DATA/H2O/P1atm/X0.01/H2O_HITEMP2010_1ATM_',I3,'K_XH_1')
102	FORMAT('../../../../LBL_DATA/H2O/P1atm/X0.01/H2O_HITEMP2010_1ATM_',I4,'K_XH_1')
	IF(ITEMP.LT.1000.D0.AND.IXG.EQ.2) WRITE(INFILE,103) ITEMP
	IF(ITEMP.GE.1000.D0.AND.IXG.EQ.2) WRITE(INFILE,104) ITEMP
103	FORMAT('../../../../LBL_DATA/H2O/P1atm/X0.1/H2O_HITEMP2010_1ATM_',I3,'K_XH_2')
104	FORMAT('../../../../LBL_DATA/H2O/P1atm/X0.1/H2O_HITEMP2010_1ATM_',I4,'K_XH_2')
	IF(ITEMP.LT.1000.D0.AND.IXG.EQ.3) WRITE(INFILE,105) ITEMP
	IF(ITEMP.GE.1000.D0.AND.IXG.EQ.3) WRITE(INFILE,106) ITEMP
105	FORMAT('../../../../LBL_DATA/H2O/P1atm/X0.2/H2O_HITEMP2010_1ATM_',I3,'K_XH_6')
106	FORMAT('../../../../LBL_DATA/H2O/P1atm/X0.2/H2O_HITEMP2010_1ATM_',I4,'K_XH_6')
	IF(ITEMP.LT.1000.D0.AND.IXG.EQ.4) WRITE(INFILE,107) ITEMP
	IF(ITEMP.GE.1000.D0.AND.IXG.EQ.4) WRITE(INFILE,108) ITEMP
107	FORMAT('../../../../LBL_DATA/H2O/P1atm/X0.4/H2O_HITEMP2010_1ATM_',I3,'K_XH_3')
108	FORMAT('../../../../LBL_DATA/H2O/P1atm/X0.4/H2O_HITEMP2010_1ATM_',I4,'K_XH_3')
	IF(ITEMP.LT.1000.D0.AND.IXG.EQ.5) WRITE(INFILE,109) ITEMP
	IF(ITEMP.GE.1000.D0.AND.IXG.EQ.5) WRITE(INFILE,110) ITEMP
109	FORMAT('../../../../LBL_DATA/H2O/P1atm/X0.6/H2O_HITEMP2010_1ATM_',I3,'K_XH_4')
110	FORMAT('../../../../LBL_DATA/H2O/P1atm/X0.6/H2O_HITEMP2010_1ATM_',I4,'K_XH_4')
	IF(ITEMP.LT.1000.D0.AND.IXG.EQ.6) WRITE(INFILE,111) ITEMP
	IF(ITEMP.GE.1000.D0.AND.IXG.EQ.6) WRITE(INFILE,112) ITEMP
111	FORMAT('../../../../LBL_DATA/H2O/P1atm/X0.8/H2O_HITEMP2010_1ATM_',I3,'K_XH_7')
112	FORMAT('../../../../LBL_DATA/H2O/P1atm/X0.8/H2O_HITEMP2010_1ATM_',I4,'K_XH_7')
	IF(ITEMP.LT.1000.D0.AND.IXG.EQ.7) WRITE(INFILE,113) ITEMP
	IF(ITEMP.GE.1000.D0.AND.IXG.EQ.7) WRITE(INFILE,114) ITEMP
113	FORMAT('../../../../LBL_DATA/H2O/P1atm/X1/H2O_HITEMP2010_1ATM_',I3,'K_XH_5')
114	FORMAT('../../../../LBL_DATA/H2O/P1atm/X1/H2O_HITEMP2010_1ATM_',I4,'K_XH_5')
	write(*,*) infile,IXG

    OPEN(1,FILE=INFILE)
    !DO I=1,12
    !READ(1,*)
    !END DO
    DO INU=1,NNU
    READ(1,*) NU(INU),K(INU,ITG)
    END DO
    CLOSE(1)
!END LOOP OVER TEMPERATURE    
    END DO
!!  END READ REFERENCE LBL DATA
!
!!!!!!!!!!!!!!!!!!!!!!!!!
!!  LOOP OVER BANDS    
!!!!!!!!!!!!!!!!!!!!!!!!!
    DO IBAND=1,NBAND
	OPEN(1000,FILE=OUTFILE(IBAND,IXG))
!!  GENERATE LOCAL ABSORPTION COEFFICIENT
    I=1
    DO INU=1,NNU !LOOP OVER WAVENUMBERS
    IF(NU(INU).GE.NUMIN(IBAND).AND.NU(INU).LT.NUMAX(IBAND)) THEN
!!  LOOP OVER TEMPERATURE
    DO ITG=1,NTG    
    KLOC(I,ITG)=K(INU,ITG)
!!  END LOOP OVER TEMPERATURE
    END DO 
    NULOC(I)=NU(INU)
    I=I+1
    END IF
    END DO !END LOOP OVER WAVENUMBERS
!   OUTPUT RESULTS
    DO INU=1,NNUB
    WRITE(1000,1010) NULOC(INU),(KLOC(INU,ITG),ITG=1,NTG)
    END DO
    CLOSE(1000)   
!!!!!!!!!!!!!!!!!!!!!!!!!
!!  END LOOP OVER BANDS    
!!!!!!!!!!!!!!!!!!!!!!!!!
    END DO
!   END  LOPP OVER COMPOSITION
    END DO    
!   FORMAT
1010 FORMAT(49(E20.10,1X),I3)
!    
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    END