        !COMPILER-GENERATED INTERFACE MODULE: Tue May 15 19:51:32 2018
        MODULE CALC_FLUXPLUSQ__genmod
          INTERFACE 
            SUBROUTINE CALC_FLUXPLUSQ
            END SUBROUTINE CALC_FLUXPLUSQ
          END INTERFACE 
        END MODULE CALC_FLUXPLUSQ__genmod
