        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 18 10:48:37 2014
        MODULE CASEGEN_mod
          INTERFACE 
            SUBROUTINE CASEGEN
          END SUBROUTINE CASEGEN
        END INTERFACE 
      END MODULE CASEGEN_mod
