        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 18 10:48:37 2014
        MODULE LECT_MSCKH_mod
          INTERFACE 
            SUBROUTINE LECT_MSCKH(JBAND)
              INTEGER(KIND=4) :: JBAND
            END SUBROUTINE LECT_MSCKH
          END INTERFACE 
        END MODULE LECT_MSCKH_mod
