        !COMPILER-GENERATED INTERFACE MODULE: Tue May 15 19:51:32 2018
        MODULE LECT_MSCKH__genmod
          INTERFACE 
            SUBROUTINE LECT_MSCKH(JBAND)
              INTEGER(KIND=4) :: JBAND
            END SUBROUTINE LECT_MSCKH
          END INTERFACE 
        END MODULE LECT_MSCKH__genmod
