        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 06 09:09:08 2014
        MODULE CLUSTERSIZE_mod
          INTERFACE 
            SUBROUTINE CLUSTERSIZE
            END SUBROUTINE CLUSTERSIZE
          END INTERFACE 
        END MODULE CLUSTERSIZE_mod
