        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 06 09:09:08 2014
        MODULE DELTACALC_mod
          INTERFACE 
            SUBROUTINE DELTACALC
            END SUBROUTINE DELTACALC
          END INTERFACE 
        END MODULE DELTACALC_mod
