        !COMPILER-GENERATED INTERFACE MODULE: Mon May 14 12:25:34 2018
        MODULE DELTACALC__genmod
          INTERFACE 
            SUBROUTINE DELTACALC
            END SUBROUTINE DELTACALC
          END INTERFACE 
        END MODULE DELTACALC__genmod
