        !COMPILER-GENERATED INTERFACE MODULE: Mon May 14 12:25:34 2018
        MODULE KMINMAX__genmod
          INTERFACE 
            SUBROUTINE KMINMAX
            END SUBROUTINE KMINMAX
          END INTERFACE 
        END MODULE KMINMAX__genmod
