        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 06 09:09:08 2014
        MODULE KMINMAX_mod
          INTERFACE 
            SUBROUTINE KMINMAX
            END SUBROUTINE KMINMAX
          END INTERFACE 
        END MODULE KMINMAX_mod
