        !COMPILER-GENERATED INTERFACE MODULE: Mon May 14 12:25:34 2018
        MODULE LECT_CDATA__genmod
          INTERFACE 
            SUBROUTINE LECT_CDATA(JBAND)
              INTEGER(KIND=4) :: JBAND
            END SUBROUTINE LECT_CDATA
          END INTERFACE 
        END MODULE LECT_CDATA__genmod
