        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 06 09:09:08 2014
        MODULE LECT_CDATA_mod
          INTERFACE 
            SUBROUTINE LECT_CDATA(JBAND)
              INTEGER(KIND=4) :: JBAND
            END SUBROUTINE LECT_CDATA
          END INTERFACE 
        END MODULE LECT_CDATA_mod
